config/routes.rb
Rails.application.routes.draw do
	root 'posts#index'

	resources :posts
	# Otro Post#show 
	get "/:id", to: "posts#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	before_validation :set_empty_title

	validates :title, length: { maximum: 13 }
	validates :slug, presence: true, uniqueness: true, length: { maximum: 13 }

	validates :url, presence: true#, length: { minimum: 2, maximum: 300 }

	extend FriendlyId
	friendly_id :title, use: :slugged


	def incrementa_visita
		self.counter+=1
		save!
	end

	private 

	def set_empty_title
		if self.title.empty?
			self.title = [*('a'..'z'),*('0'..'9')].shuffle[0,5].join
			self.empty_title = true
		end
	end

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@post = Post.new
	end

	def create 
		@post = Post.new(strong_params)
		if @post.save
	      respond_to do |format|      
	      	format.html { redirect_to @post, notice: 'El post fue creado!' }
	        format.js 
	      end
	    end
	end

	def show
		@post = Post.friendly.find(params[:id])
		@post.incrementa_visita

		@video_exist = (@post.url.start_with?("https://video.flim")) ? true : false 
	end



	private 

	def strong_params
		params.require(:post).permit(:title, :url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onegaistream</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>

  <body>
  	<header class="header main-center cross-center">
      <h1 class="header__title">
        <%= link_to "O.li", root_path, class: "header__link" %>
      </h1>
      <h2 class="header__subtitle">the best shortening of urls</h2>
    </header>
    
    <div class="main-container">
      <%= yield %>
    </div>

    <footer class="footer">
      <p>© 2018 Oli™</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with( model: @post, :html => {id: "posts-form", class:"ed-container main-center main-form"}) do |f| %>
	
	<div class="ed-item m-75 s-100">
		<%= f.text_field :url, required: true, class: "main-form__url", placeholder: "Pega aquí tu url original ..." %>
	</div>
	<div class="ed-item m-25 s-100">
		<%= f.submit "ACORTA LA URL", class: "main-form__submit" %>
	</div>
	
	<div class="opcional-form ed-container">
		<div class="ed-item">
			<label>Opcional: <span>o.li/</span></label>
			<%= f.text_field :title, placeholder: "url-personalizada", class: "opcional-form__title" %>
		</div>
	</div>

<% end %>

app/views/posts/_post_ajax.html.erb
<div class="confirmacion__item ed-item full">
	<% post_url = request.base_url + "/" + @post.slug %>
	<%= link_to post_url, post_url, target: '_new', class: "confirmacion__link" %>
</div>
<style type="text/css">
.confirmacion
{
	display: block;
}
</style>

app/views/posts/create.js.erb
$('#confirmacion').append('<%= j render "post_ajax" %>')

app/views/posts/index.html.erb
<div class="main-page">
	<div>
		<%= render "form" %>
	
		<div id="confirmacion" class="ed-container confirmacion"></div>

		<% if @video_exist  %>
			<video src="<%= @post.url %>"></video>
		<% else %>
			<p><%= @post.url %></p>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div>
	<div>
		<p class="visto">Visto <%= @post.counter %> veces</p>

		<% if @video_exist  %>
			<video src="<%= @post.url %>"></video>
		<% else %>
			<p><%= @post.url %></p>
		<% end %>
	</div>
</div>